"""add constraint on tag name

Revision ID: 78f233d5cd8c
Revises: 869910166232
Create Date: 2026-07-20 13:17:10.272284

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78f233d5cd8c"
down_revision: str | Sequence[str] | None = "869910166232"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_user_id_name", "tags", ["user_id", "name"])
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint("uq_user_id_name", "tags", type_="unique")
    # ### end Alembic commands ###
